### ISSUE TITLE
Update Cart Service to use Infinispan protostream-processor to auto generate proto schemas

### ISSUE THREAD

**Issue by rafaeltuelho** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-labs#9]
Leverage the *protostream-processor* and *Serialization Context Initializers* as described in [1] to auto-generate proto marshallers...

[1] https://infinispan.org/docs/10.1.x/titles/developing/developing.html#generating_proto_marshallers

**Comment by sshaaf** [comment]
This could most likely be either added as part of the exercise. or could be documented in the labs. since the goal of this exercise was to get into some more details around the process and user written serialization.

**Comment by danieloh30** [comment]
Thanks for the comment, @sshaaf.

I will close this issue now. Please reopen the issue or add comments if you have more questions.

**Comment by sshaaf** [comment]
Marshallers are now deprecated. in the next update I plan to remove them and move to annotations.

**Comment by rafaeltuelho** [comment]
Also, the image `jboss/infinispan-server` is deprecated as well. We should use `infinispan/server` instead.

**Comment by sshaaf** [comment]
If we are not using the operator. we should do that now. At the time of writing I believe we did not have an Operator GA.

**Comment by sshaaf** [comment]
@danieloh30 we will now need to update the docs too

**Comment by danieloh30** [comment]
Ok. I updated guides as well as lab code to apply for the annotation based serialization.
